services:
  
  backend:
    build: ./backend
    container_name: calculator-backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: calculator-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend


  