name: Project CI/CD

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main


permissions:
  contents: read


jobs:

# =========================
# Backend Test + Docker
# =========================

  backend-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend


    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json


      - name: Install dependencies
        run: npm install


      - name: Run backend tests
        run: npm test


      - name: Generate coverage
        run: npm run test:coverage


      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage/


      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true

          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/calculator-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/calculator-backend:${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max



# =========================
# Frontend Test + Docker
# =========================


  frontend-test:

    runs-on: ubuntu-latest


    defaults:
      run:
        working-directory: frontend


    steps:


      - name: Checkout code
        uses: actions/checkout@v4



      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json



      - name: Install dependencies
        run: npm install



      - name: Run frontend tests
        run: npm test



      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3



      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:

          context: ./frontend

          push: true

          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/calculator-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/calculator-frontend:${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max